name: update
on:
  push:
    tags:
      - 'releases/v**'

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm
          
      - name: Install dependencies
        run: npm install
      
      - name: Run test
        run: npm test
      
      - name: Collect Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
    # give the id for the step, to access outputs in another step.
        id: coverage
        with:
        # tell to the action to not attach comment.
          output: report-markdown
          
      - name: report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
        # pass output from the previous step by id.
          message: ${{ steps.coverage.outputs.report }}

      - name: Publish update
        run: eas update --auto
